# Searching for the category

For this code along we are only going to use the products DataFrame. However, if you believe there is information in other tables that can help to create categories, please feel free to explore.

In [1]:
import pandas as pd

In [4]:
# products_cl.csv
url = "https://drive.google.com/file/d/1IPnKYLSnrST0HBZMeSeNrhFfWU31QvwB/view?usp=drive_link"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
products_cl = pd.read_csv(path)

In [5]:
product_category_df = products_cl.copy()

In [6]:
product_category_df.head()

,sku,name,desc,price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,0,13855401
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,0,1387
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,0,1230
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,1,1364

## 1.&nbsp; Category creation by search term
Let's start by creating a column `category`. For now we'll fill this column with a blank string `""`.

In [8]:
product_category_df["category"] = ""
product_category_df.head()

,sku,name,desc,price,in_stock,type,category
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696,
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,0,13855401,
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,0,1387,
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,0,1230,
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,1,1364,

We can find all the products with certain words in their `description` using `.loc[]` and `.str.contains()`. Here we'll look at all the items that have the word `keyboard` in their description.

In [9]:
product_category_df.loc[product_category_df["desc"].str.contains("keyboard", case=False)]

,sku,name,desc,price,in_stock,type,category
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,0,13855401,
15,MOS0021,Clearguard Moshi MacBook Pro and Air,Keyboard Protector MacBook Pro 13-inch Retina ...,24.95,0,13835403,
24,APP0277,Apple Wireless Keyboard Keyboard (OEM) Mac,Ultrathin keyboard Apple Bluetooth Spanish (un...,79.00,0,13855401,
64,HGD0012,Henge Docks Click keyboard support iMac,Base to hold the Apple Magic TrackPad and Wire...,29.00,0,8696,
365,LOG0084,Logitech Ultrathin Keyboard Cover Keyboard Cov...,Ultrathin cover and cover with Bluetooth keybo...,89.99,0,12575403,
...,...,...,...,...,...,...,...
9720,PAC2508,Replacement Magic Wireless Keyboard by Matias ...,Keyboard replacement service at the time of pu...,119.99,1,13855401,
9751,MTF0008,Mistify Clean Screens Natural 500ml.,Spray cleaning screens and keyboards.,14.99,1,12085400,
9796,ZAG0026-A,Open - Zagg Rugged Keyboard Folio iPad Messeng...,Case reconditioned keyboard and adjustable pos...,99.99,0,12575403,
9932,APP1472,Apple Magic Keyboard English International,English keyboard Mac and Apple iPad Ultrathin ...,119.00,1,13855401,
9945,TWS0106-A,Open - Twelve South Bridge Magic Keyboard for ...,Light reconditioned support to hold the Keyboa...,48.00,0,8696,

Next, we change the value in the category column to `keyboard` for all of these keyboard products.

In [10]:
product_category_df.loc[product_category_df["desc"].str.contains("keyboard", case=False), "category"] = "keyboard"

Let's take a look at the effect that had on the `category` column.

In [11]:
product_category_df["category"].value_counts()

category
            9903
keyboard      89
Name: count, dtype: int64

## 2.&nbsp; Category creation using regex
We can also use a product's `name` to select products for our categories.

In [12]:
product_category_df.loc[product_category_df["name"].str.contains("apple iphone", case=False)]

,sku,name,desc,price,in_stock,type,category
35,APP0308,AV Cable Adapter Apple iPhone iPad and iPod white,IPhone iPad iPod adapter and AV cable.,45.00,0,1230,
214,REP0100,Color change to White Apple iPhone 4,It is including parts and labor..,94.21,0,"1,44E+11",
215,REP0052,Color change to White Apple iPhone 4,It is including parts and labor..,94.21,0,"1,44E+11",
579,APP0675,Apple iPhone 5S 32GB Space Gray,New Free iPhone 5S 32GB (ME435Y / A).,559.00,0,NaN,
956,APP0823,Apple iPhone 6 16GB Silver,New iPhone 6 16GB Free (MG482QL / A).,639.00,0,NaN,
...,...,...,...,...,...,...,...
9790,AP20455,Like new - Apple iPhone 8 256GB Gold,Apple iPhone 8 reconditioned 256GB in Gold rea...,979.00,0,113291716,
9794,APP2482-A,Open - Apple iPhone 8 Plus 256GB Gold,Refurbished Apple iPhone 8 Plus 256GB Free Gold,1089.00,0,113281716,
9929,APP2477-A,Open - Apple iPhone 8 Plus 64GB Space Gray,Apple iPhone 8 Plus 64GB Space Gray,919.00,0,113281716,
9958,AP20467,Like new - Apple iPhone Silicone Case Cover 7 ...,Reconditioned silicone sleeve microfiber Apple...,45.00,0,11865403,
9969,AP20468,Like new - Apple iPhone Black Lightning Dock,Support base and refitted with dock connector ...,59.00,0,13615399,

Looks like we get a lot of accessories included in this search. We can refine this using a little regex. Here, we will add `.{0,7}` at the beginning of the search: this means we will find all `apple iphone`s that have 7 or less characters preceding the term "apple iphone" - if there's 8 characters preceding the search term, it won't be found. This should help refine our search by using the nomenclature of the DataFrame to our advantage.

If you feel unsure about regex, please use [regex101](https://regex101.com/). It's really useful for checking your code, and parts of other people's code that you're unsure about.

In [13]:
product_category_df.loc[product_category_df["name"].str.contains("^.{0,7}apple iphone", case=False)]

,sku,name,desc,price,in_stock,type,category
579,APP0675,Apple iPhone 5S 32GB Space Gray,New Free iPhone 5S 32GB (ME435Y / A).,559.0,0,NaN,
956,APP0823,Apple iPhone 6 16GB Silver,New iPhone 6 16GB Free (MG482QL / A).,639.0,0,NaN,
961,APP0829,Apple iPhone 6 Plus 16GB Silver,New iPhone 6 Plus 16G Free (MGA92QL / A).,749.0,0,NaN,
962,APP0822,Apple iPhone 6 16GB Space Gray,New iPhone 6 16GB Free (MG472QL / A).,639.0,0,NaN,
963,APP0825,Apple iPhone 6 64GB Space Gray,New iPhone 6 64GB Free (MG4F2QL / A).,749.0,0,NaN,
...,...,...,...,...,...,...,...
9585,APP1634-A,Open - Apple iPhone 7 Plus 32GB Black,New 32GB Apple iPhone 7 Plus Free Black,779.0,0,85651716,
9587,APP2540-A,Open - Apple iPhone Leather Folio X Baya,Leather case with box and official cover Apple,109.0,0,11865403,
9714,APP2562-A,Open - Apple iPhone Leather Case Cover Red,Reconditioned skin sheath official Apple desig...,45.0,0,11865403,
9794,APP2482-A,Open - Apple iPhone 8 Plus 256GB Gold,Refurbished Apple iPhone 8 Plus 256GB Free Gold,1089.0,0,113281716,
9929,APP2477-A,Open - Apple iPhone 8 Plus 64GB Space Gray,Apple iPhone 8 Plus 64GB Space Gray,919.0,0,113281716,

Now we can use the same trick as before to set the category - selecting the `category` column and setting it to the string of our choice.

In [14]:
product_category_df.loc[product_category_df["name"].str.contains("^.{0,7}apple iphone", case=False), "category"] = "smartphone"

In [15]:
product_category_df["category"].value_counts()

category
              9634
smartphone     269
keyboard        89
Name: count, dtype: int64

## 3.&nbsp; One product with multiple categories
A product may fit into multiple categories. To help us create multiple categories for one product, we will use the python addition assignment `+=`. The addition assignment is a shorthand way to add something (number, string, etc...) to a variable without changing the variable name.

Let's have a look at a couple of examples.

In [ ]:
a = 10
a = a + 5
a

15

In [ ]:
a = 10
a += 5
a

15

In [ ]:
b = "Tyrannosaurus"
b = b + " rex"
b

'Tyrannosaurus rex'

In [ ]:
b = "Tyrannosaurus"
b += " rex"
b

'Tyrannosaurus rex'

Now let's look at how this can help us in our category creation.

First, we'll reset all the values in the category column to an empty string `""`.

In [ ]:
product_category_df["category"] = ""

Now, let's create some categories and utilise the addition assignment.

In [ ]:
product_category_df.loc[product_category_df["desc"].str.contains("keyboard", case=False), "category"] += ", keyboard"
product_category_df.loc[product_category_df["name"].str.contains("^.{0,7}apple iphone", case=False), "category"] += ", smartphone"
product_category_df.loc[product_category_df["name"].str.contains("^.{0,7}apple ipod", case=False), "category"] += ", ipod"
product_category_df.loc[product_category_df["name"].str.contains("^.{0,7}apple ipad|tablet", case=False), "category"] += ", tablet"
product_category_df.loc[product_category_df["name"].str.contains("imac|mac mini|mac pro", case=False), "category"] += ", desktop"

In [ ]:
product_category_df["category"].value_counts()

                       8362
, desktop               923
, tablet                307
, smartphone            269
, keyboard               83
, ipod                   42
, keyboard, tablet        4
, keyboard, desktop       2
Name: category, dtype: int64

As you can see, some products now have 2 categories instead of just one. At the end, you can use your skills with string to tidy up the opening comma and space in the `category` column.

# Challenge. Your categories
Now it's your turn. We'll reset the Dataframe so that no categories exist, and it's up to you to create the categories based on keywords in the name and description. Feel free to go wild and make as many categories as you like.
* Remember you can also use regex to refine your searches.
* Remember you can use the or operator `|` to search for multiple terms at once.
* Remember to tidy up any untidy strings at the end.

In [57]:
# resetting to original import
product_category_df = products_cl.copy()

In [58]:
# your code here
product_category_df["category"] = ""
product_category_df.head()

,sku,name,desc,price,in_stock,type,category
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696,
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,0,13855401,
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,0,1387,
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,0,1230,
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,1,1364,

## 4.&nbsp; [BONUS] Using `type` to create categories
There could be another way to create categories, but this one you'll have to explore this one alone.

We have the mysterious column `type` in the `products` table. This could potentially be ready-made categories labelled with numbers instead of words. Let's investigate.

In [59]:
category_type_df = products_cl.copy()

In [102]:
category_type_df["type"].unique

<bound method Series.unique of 0           8696
1       13855401
2           1387
3           1230
4           1364
          ...
9987       12282
9988        1392
9989        1392
9990        1392
9991        1392
Name: type, Length: 9992, dtype: str>

Here are the `type`s that have the most products.

In [60]:
category_type_df.groupby("type").count().nlargest(30, "sku")

           sku  name  desc  price  in_stock
type
11865403  1057  1057  1057   1057      1057
12175397   939   939   939    939       939
1298       783   783   783    783       783
11935397   562   562   562    562       562
11905404   454   454   454    454       454
1282       373   373   373    373       373
12635403   362   362   362    362       362
13835403   269   269   269    269       269
5,74E+15   247   247   247    247       247
1364       216   216   216    216       216
12585395   190   190   190    190       190
1296       187   187   187    187       187
1325       183   183   183    183       183
5384       178   178   178    178       178
1433       171   171   171    171       171
12215397   170   170   170    170       170
5398       159   159   159    159       159
1,02E+12   130   130   130    130       130
1,44E+11   129   129   129    129       129
57445397   129   129   129    129       129
1334       115   115   115    115       115
2158       107   107   107    107       107
2449       107   107   107    107       107
12655397   105   105   105    105       105
1229       104   104   104    104       104
12995397    95    95    95     95        95
1515        85    85    85     85        85
13615399    78    78    78     78        78
13555403    75    75    75     75        75
1405        75    75    75     75        75

Let's have a look at the first `type` to see if we can make categories from this column.

In [99]:
category_type_df.loc[category_type_df["type"] == "11865403"].sample(10)

,sku,name,desc,price,in_stock,type
5121,OTT0147,Otterbox iPhone Case Symmetry 8 Plus / 7 Plus ...,resistant cover and thin beveled edges for iPh...,39.99,1,11865403
5269,MOS0204,Moshi iGlaze iPhone Armor Case 7 Black Metal,protective cover two colors with metallic acce...,40.00,1,11865403
8896,OTT0180,OtterBox iPhone Case Etui Symmetry Black 8,Symmetry OtterBox protective sleeve one-piece ...,34.99,0,11865403
8869,TCH0012,Tech21 Evo Check Case iPhone X Rosa,X iPhone case studied to overcome multiple dro...,39.99,1,11865403
3521,MOS0177,Moshi iGlaze Case Luxe iPhone 6 / 6S Orange,acrólico transparent protective case for iPhon...,55.00,0,11865403
7966,AP20271,Like new - Apple Leather Case Cover iPhone 6 P...,ultrathin leather case and microfiber top qual...,59.00,0,11865403
3956,MAC0121,Macally Snap-on Case iPhone 6 / 6S metallic red,Case rigid and resistant metallic tones iPhone...,9.95,1,11865403
966,APP0832,Apple iPhone 6 Plus Case White,Ultrathin silicone case and microfiber premium.,39.00,0,11865403
5263,MOS0197,Moshi iGlaze Case Black iPhone 7/8,rigid case with compact design and shock prote...,30.00,1,11865403
8238,TUC0344,Denso Tucano iPhone Case Black Mil-Std X,military-grade protection without sacrificing ...,26.90,1,11865403

Looks like this is a category of phone cases.

Let's have a look at the 2nd largest type to see if that's also a clear category.

In [62]:
product_category_df.loc[product_category_df["type"].str.contains("11865403", case=False), "category"] = "phone_cases"
product_category_df["category"].value_counts()

category
               8935
phone_cases    1057
Name: count, dtype: int64

In [63]:
category_type_df.loc[category_type_df["type"] == "12175397"].sample(10)

,sku,name,desc,price,in_stock,type
8498,PAC2407,DS418play Synology NAS Server | 10GB RAM | 32T...,4-bay NAS server to accommodate 4K Ultra HD files,2041.31,0,12175397
6014,QNA0198,QNAP TS-831X Server Nas | 8GB RAM,8-bay NAS server for business environment with...,930.49,0,12175397
1322,PAC0599,Synology DS1815 Pack + | WD 16TB Network,Pack Synology DS1815 + 16TB Hard Drive WD Netw...,1908.97,0,12175397
8836,PAC2303,Synology DS118 NAS Server | 8TB (1x8TB) WD Red,1 bay NAS server with capacity for home use or...,534.99,0,12175397
4393,PAC1403,Synology DS716 + II Pack | 2GB RAM | Seagate 6...,Synology DS716 + II with 2GB of RAM memory + 6...,751.88,0,12175397
3272,PAC1632,Pack QNAP TS-251 + | 2GB RAM | Seagate NAS 16TB,TS-251 + Nas with 2GB RAM memory + 20TB (2x10T...,1148.98,1,12175397
3887,PAC1359,Synology DS216 + Pack | Seagate NAS 6TB,NAS + 6TB (2x3TB) NAS Seagate for Mac and PC.,630.99,0,12175397
8813,PAC2455,DS218J Synology NAS Server | 4TB (2x2TB) Seaga...,2-bay NAS server entry-level to back domestic ...,405.97,0,12175397
8622,PAC2271,Synology DS918 + NAS Server | 12GB | 8TB (4x2T...,NAS server of the Plus Series for companies se...,1077.35,0,12175397
3656,PAC1267,Pack QNAP TS-251 | 4GB RAM | Seagate 4TB Desktop,Pack QNAP TS-251 with 4GB RAM + 4TB (2x2TB) Se...,577.98,0,12175397

Looks like this category is full of servers.

In [64]:
product_category_df.loc[product_category_df["type"].str.contains("12175397", case=False), "category"] = "servers"
product_category_df["category"].value_counts()

category
               7996
phone_cases    1057
servers         939
Name: count, dtype: int64

In [100]:
category_type_df.loc[category_type_df["type"] == "1298"].sample(30)

,sku,name,desc,price,in_stock,type
6374,APP1374-A,"Open - Apple iMac 27 ""Core i7 Retina 5K 4GHz |...",IMac desktop computer 27 inch 8GB RAM 512GB Re...,3169.00,0,1298
6495,KUA0018-A,Open - Kukaclip Support Case Car + iPhone 6 / ...,Magnetic car holder with 360 degrees rotating ...,24.99,0,1298
6173,WDT0347-A,Open - WD My Passport 1TB External Hard Drive ...,1TB External Hard Drive USB 3.0 with Mac and P...,89.99,0,1298
8084,TUC0306-A,Open - Tucano Nido Hard-Shell Case MacBook Pro...,Protective cover with slip rubber feet for Mac...,34.90,0,1298
8091,SAN0129-A,Open - Sandisk iXpand Lightning to USB 3.0 128GB,128GB storage unit for iPhone and iPad,99.99,0,1298
6971,OWC0180-A,"Open - OWC Accelsior S Adapter PCIe 2.5 ""Sata ...",PCI Express SSD for Mac Pro up to 51 (mid 2006...,78.99,0,1298
6463,APP1659-A,Open - 32GB Apple iPhone 6s Rose Gold,New iPhone 6S 16GB Free,529.00,0,1298
6491,TUC0186-A,Open - Angolo Tucano Folio iPad Air 2 Black,Zippered sleeve type book for iPad Air 2.,34.99,0,1298
6249,APP1717-A,Open - Apple Watch 42mm Aluminum Case Series 2...,Apple Watch 42 mm dual core processor with GPS...,469.00,0,1298
4861,WDT0302-A,(Open) Western Digital Elements Desktop USB 3....,Elegant and lightweight external hard 4TB disk...,149.99,0,1298
8087,BEL0262-A,Open - Belkin RockStar MIXIT Power Battery 100...,Portable external battery compartment for cabl...,99.99,0,1298
6332,WOE0007-A,Open - Wowewa Power Bank 3000mAh External Batt...,3000mAh external battery light and compact (77...,19.99,0,1298
6662,LEX0028-A,Open - Lexar JumpDrive Lightning USB 3.0 C20i ...,Lightning to USB external memory for iPad and ...,108.90,0,1298
6042,KUA0016-A,Open - Kukaclip Support Case Car + iPhone 6 / ...,Magnetic car holder with 360 degrees rotating ...,24.99,0,1298
2993,NTE0022-A,Open - NewerTech Mini DVI to VGA Adapter,Mini DVI to VGA.,18.99,0,1298
1445,WDT0175-A,"Open - Western Digital 2TB Green 35 ""5400rpm h...",WD Internal Hard Drive 2TB Mac and PC.,90.00,0,1298
6415,LAC0179-A,Open - 2TB LaCie Rugged USB 3.0 Thunderbolt,Wireless Portable Hard Thunderbolt and USB 3.0...,204.99,0,1298
6135,PHI0066-A,Open - Philips Hue White Set 2 bulbs 9.5W E27 ...,Kit 2 + bridge white bulbs illuminated HUE,79.95,0,1298
5488,TRK0003-A,Open - Bravo Locator Silver Trackr,Bluetooth locator objects APP for iPhone,29.99,0,1298
5067,MAC0120-A,(Open) U3HUBA Macally USB 3.0 4-Port Hub,Hub 4 ports USB 3.0 High Speed ​​for Mac and PC,34.95,0,1298
3308,ADN0027-A,(Open) Adonith Stylus Pointer Black Dash,Professional pointer for iPad iPod and iPhone.,49.99,0,1298
2968,KAN0012-A,(Open) Kanex Lightning to USB Cable 3m White,Lightning USB cable to charge and sync iPhone ...,27.95,0,1298
7863,JMO0084-A,Open - Just Mobile AutoHeal protector Crystal ...,Polyester screen saver and autoheald for iPhon...,19.99,0,1298
2374,XDO0013-A,(Open) X-Doria Lux Apple Watch Strap Black 42mm,Leather strap for easy installation Apple Watch.,49.99,0,1298
5540,LAC0193-A,Open - LaCie Rugged Triple Hard Drive 1TB USB ...,Portable Hard Drive drop resistant double conn...,124.99,0,1298
6345,TWS0040-A,Open - Twelve South BookBook Case iPhone 5 / 5...,Funda iPhone 5 / 5S vintage leather with padde...,49.99,0,1298
3597,JBL0097-A,(Open) Bluetooth Alarm Clock Speaker JBL Horiz...,Bluetooth speaker with clock 2 USB ports and L...,99.99,0,1298
6957,WAC0215-A,Open - Wacom Intuos Graphics Tablet Pro M Sout...,Medium graphics tablet includes Bluetooth Intu...,379.90,0,1298
6540,PHI0058-A,Open - Philips Hue Starter Kit Pack 3 White li...,Kit 3 white light bulbs and color light contro...,199.95,0,1298
6714,WAC0218-A,Open - Wacom Intuos Pro L South Graphics Tablet,Bluetooth includes large graphics tablet Intuo...,529.90,0,1298

Looks like this category is full of open accessories.

In [101]:
product_category_df.loc[product_category_df["type"].str.contains("1298", case=False), "category"] = "open_accessories"
product_category_df["category"].value_counts()

category
                     4170
phone_cases          1057
servers               939
open_accessories      783
storage               562
smart_devices         454
laptops               373
ipad_cases            362
computer_cases        269
desktop_computers     247
ram_memories          216
adapters              190
monitors              187
cables                183
Name: count, dtype: int64

In [67]:
category_type_df.loc[category_type_df["type"] == "11935397"].sample(10)

,sku,name,desc,price,in_stock,type
562,OWC0088,OWC Mercury Elite Pro QX2 aluminum box eSata /...,Mac and PC RAID 4 bay with connection eSata / ...,362.99,0,11935397
2360,WDT0269,Western Digital My Passport Ultra 3TB hard dri...,External Hard Drive USB 3.0 3TB Mac and PC.,149.99,0,11935397
3512,DRO0025,B810N Drobo 8-bay NAS RAID,NAS with RAID 2-Port Ethernet 8-bay for Mac an...,1939.00,0,11935397
1787,TRA0032,Transcend StoreJet SSD 500 External Hard Drive...,External Hard Drive 1TB SSD with Thunderbolt a...,911.00,0,11935397
5872,WDT0353,1TB WD My Passport 25 USB 3.0 External Hard Dr...,1TB External Hard Drive USB 3.0 with Mac and P...,89.99,0,11935397
5287,SAN0154,SanDisk Ultra Fit Flash Drive 16GB USB 3.0,Pendrive 16GB ultra-compact USB 3.0 transfers ...,9.99,0,11935397
8040,LAC0239,Lacie Rugged USB Disk Thunderbolt SSD 1TB-C,"1TB SSD rugged, compact Thunderbolt and USB-C ...",629.99,0,11935397
2309,SAN0090,Sandisk 32GB Flash Drive Pen Drive USB-C,32GB pendrive reversible USB-C to USB for Mac ...,49.99,0,11935397
5894,WDT0373,"WD My Book external hard drive 6TB 35 ""USB 3.0",6TB external hard drive with USB 3.0 connectio...,229.99,0,11935397
8794,GTE0124,G-Technology G-DRIVE HDD 12TB 7200rpm Thunderb...,12TB Hard disk with 2 USB 3 and Thunderbolt co...,787.99,0,11935397

Looks like this category is full of storage products (or hard drives).

In [68]:
product_category_df.loc[product_category_df["type"].str.contains("11935397", case=False), "category"] = "storage"
product_category_df["category"].value_counts()

category
                        6651
phone_cases             1057
servers                  939
hardware_accessories     783
storage                  562
Name: count, dtype: int64

In [72]:
category_type_df.loc[category_type_df["type"] == "11905404"].sample(10)

,sku,name,desc,price,in_stock,type
1484,RUT0008,Runtastic White Libra Scale,Smart Scale for iPhone and iPad.,129.99,0,11905404
1191,PAC0548,Avea Pack 2 units Elgato Smart Bulb,Pack of 2 bulbs bluetooth multimode light for ...,79.98,0,11905404
2287,IKM0046,IK Multimedia iRig Mic Studio Plata,Portable digital large diaphragm microphone fo...,219.59,0,11905404
297,WAH0007,Wahoo Fitness BlueSC cadence and speed sensor,iPhone wireless sensor cadence and speed for c...,59.99,1,11905404
794,NEA0009,Netatmo home thermostat for iPhone and iPad,Thermostat iPhone iPad wifi Mac design Stark.,179.00,0,11905404
8456,NIE0010,Segway personal transport MiniLite,Robot two-wheeled personal transport up to 18K...,399.00,0,11905404
2461,PAR0049,Mc Clane Parrot Drone Airborne Night Blue,Cuadricóptero night Drone remote control with ...,129.90,0,11905404
1314,MUV0154,Muvit timer for photos and audio control iPhone,Trigger for photos and Bluetooth audio driver ...,29.95,0,11905404
2159,JAW0038,Jawbone UP2 Activity Monitor Black,Bluetooth monitor activity and sleep with pers...,119.99,0,11905404
1631,PHI0055,Philips HUE TAP switch to control scenes,Intelligent wireless switch to Philips HUE.,59.99,0,11905404

Looks like this category is full of smart devices & electronics.

In [73]:
product_category_df.loc[product_category_df["type"].str.contains("11905404", case=False), "category"] = "smart_devices"
product_category_df["category"].value_counts()

category
                           6197
phone_cases                1057
servers                     939
it_hardware_accessories     783
storage                     562
smart_devices               454
Name: count, dtype: int64

In [74]:
category_type_df.loc[category_type_df["type"] == "1282"].sample(10)

,sku,name,desc,price,in_stock,type
539,PAC0860,Apple Mac Pro 12-core 27 Ghz | 32GB RAM | 512G...,New Mac Pro with 32GB of RAM 12-core GPU 6GB 5...,9689.0,0,1282
1730,APP0973,"Apple MacBook Pro Retina 13 ""i5 29 Ghz | 16GB ...",New MacBook Pro 13-inch Retina display 16GB RA...,2839.0,0,1282
1134,APP1029,Apple Mac mini Core i7 3GHz | 16GB RAM | 512GB...,PC Mac mini Core i7 3GHz 16GB 512GB Flash (MGE...,1819.0,1,1282
7904,AP20239,"Like new - Apple MacBook Pro 13 ""with Touch Ba...",Refurbished MacBook Pro 13-inch Touch Bar 29 G...,2199.0,0,1282
2774,APP1232,"Apple iMac 215 ""Core i5 16GHz | 8GB | 256GB Fl...",IMac desktop computer 215 inch 8GB RAM 256GB F...,1579.0,0,1282
2736,PAC1585,"Apple iMac 21.5 ""Core i7 3.3GHz 4K Retina | 16...",Desktop computer iMac 21.5-inch 3.3GHz Core i7...,3649.0,0,1282
4236,APP1579,"Apple MacBook Retina 12 ""Core m5 12GHz | 8GB R...",New MacBook Retina Display 12-inch Core 8GB RA...,1799.0,0,1282
6790,PAC1930,"Second hand - Apple iMac 215 ""Core i5 Quad-Cor...",IMac used i5 215 inch quad-core 27GHz | 8GB RA...,1199.0,0,1282
7053,PAC2065,"Second hand - Apple iMac 24 ""Core 2 Duo 28 GHz...",Computer Refurbished iMac 24 inch Core 2 Duo 2...,1799.0,0,1282
1136,APP1930,Apple Mac mini Core i7 3GHz | 16GB RAM | 1TB F...,Apple desktop Mac mini Core i7 3GHz | 16GB RAM...,2299.0,0,1282

Looks like this category is full of laptops (MacBook).

In [82]:
product_category_df.loc[product_category_df["type"].str.contains("1282", case=False), "category"] = "laptops"
product_category_df["category"].value_counts()

category
                           5193
phone_cases                1057
servers                     939
it_hardware_accessories     783
storage                     562
smart_devices               454
laptops                     373
ipad_cases                  362
computer_cases              269
Name: count, dtype: int64

In [77]:
category_type_df.loc[category_type_df["type"] == "12635403"].sample(10)

,sku,name,desc,price,in_stock,type
1176,APP0915,Apple Smart Case iPad Air 2 Case Soft Pink,Smart Leather Case for iPad Air 2.,89.00,0,12635403
2922,GRT0382,Griffin Folio iPad Mini Turn 4 Blue,Mini iPad sleeve type book support.,34.99,0,12635403
9956,DVI0013,"Devia Grace Light iPad Case 97 ""(2017) Rosa",Case rigid transparent front cover rear cover ...,29.99,0,12635403
8294,AP20339,"Like new - Apple iPad Smart Cover Pro 97 ""Alba...",reconditioned smart cover with different posit...,59.00,0,12635403
2955,APP1440,Apple Smart Cover iPad Mini 4 Rosa,Polyurethane Smart Cover iPad Mini 4.,45.00,0,12635403
2921,GRT0381,Turn Griffin Folio iPad Mini 4 Black,Funda iPad Mini 4 type book support.,34.99,0,12635403
2887,OTT0123,Otterbox iPad Folio Symmetry Air 2 Black,Protective Case Folio format for iPad Air 2.,99.99,0,12635403
7225,TUC0316,"Filo Minerale Tucano iPad Case 97 ""Silver",Resistant cover front cover with magnetic clos...,39.90,0,12635403
1380,TWS0071,Twelve South iPad mini 2/3 SurfacePad Classic ...,Leather Case for iPad Mini.,69.99,0,12635403
4066,APP1537,"Apple iPad Silicone Case Pro 97 ""Menta",Silicone light cover and soft touch for iPad P...,79.00,0,12635403

Looks like this category is full of ipad cases.

In [78]:
product_category_df.loc[product_category_df["type"].str.contains("12635403", case=False), "category"] = "ipad_cases"
product_category_df["category"].value_counts()

category
                           5462
phone_cases                1057
servers                     939
it_hardware_accessories     783
storage                     562
smart_devices               454
computers                   373
ipad_cases                  362
Name: count, dtype: int64

In [79]:
category_type_df.loc[category_type_df["type"] == "13835403"].sample(10)

,sku,name,desc,price,in_stock,type
9369,ICA0100,"Incase Case Diamond MacBook Pro 15 ""Black",Incase Diamond Case with magnetic closure and ...,69.95,1,13835403
4546,THU0044,"Thule Stróvan MacBook Sleeve Case 15 ""(Pro and...",Compartmientos cover with pockets for MacBook ...,49.95,0,13835403
6126,TUC0310,"Tucano Nido Hard-Shell Case MacBook Pro 13 ""(L...",Protective cover with slip rubber feet 13 inch...,29.90,1,13835403
8922,MMW0021,"My MacBook Air 13 MW Case ""Peach",Avoid shock and damage to your MacBook Air 13-...,29.95,0,13835403
4539,THU0036,"Thule Subterra Sleeve Case MacBook Air 11 ""Black",Case with outside pocket and zippered MacBook ...,49.95,1,13835403
1467,AII0065,"Aiino housing MacBook Air 13 ""Blue Mate",Protective housing MacBook Air 13 inches.,34.99,0,13835403
9766,KNO0024,"Knomo Leather MacBook Case Barbican 13 ""Black",Elegant leather case for MacBook Pro 13-inch a...,99.00,0,13835403
2286,MOS0165,"Moshi iGlaze housing Macbook Retina 12 ""Transp...",MacBook resistant protective casing 12 inches.,49.99,0,13835403
9712,TUC0302-A,"Tucano Nido Hard-Shell Case MacBook Pro 13 ""(l...",Open - Tucano Nido Hard-Shell Case 13-inch Mac...,29.90,0,13835403
1419,BEZ0180,Be.ez LArobe MacBook Pro Retina sleeve ONE 13 ...,Neoprene Sleeve for MacBook Pro Retina 13 inches.,29.95,0,13835403

Looks like this category is full of computer cases.

In [80]:
product_category_df.loc[product_category_df["type"].str.contains("13835403", case=False), "category"] = "computer_cases"
product_category_df["category"].value_counts()

category
                           5193
phone_cases                1057
servers                     939
it_hardware_accessories     783
storage                     562
smart_devices               454
computers                   373
ipad_cases                  362
computer_cases              269
Name: count, dtype: int64

In [83]:
category_type_df.loc[category_type_df["type"] == "5,74E+15"].sample(10)

,sku,name,desc,price,in_stock,type
7291,PAC2074,"Apple iMac 27 ""Core i5 Retina 5K 34GHz | 16GB ...",IMac desktop computer 27 inch Retina 5K RAM 16...,2579.00,0,"5,74E+15"
7261,PAC2104,"Apple iMac 27 ""Core i5 3.5GHz Retina 5K | 64GB...",IMac desktop computer 27 inch Retina 5K RAM 64...,4339.00,0,"5,74E+15"
7268,PAC2083,"Apple iMac 27 ""Core i7 42GHz 5K Retina | 32GB ...",IMac desktop computer 27 inch Retina 5K RAM 32...,3565.59,0,"5,74E+15"
2664,PAC1056,"Apple iMac 27 ""Core i5 3.3GHz Retina 5K | 16GB...",IMac desktop computer 27 inch 5K Retina i5 3.3...,3289.00,0,"5,74E+15"
2703,PAC1627,"Apple iMac 27 ""Core i7 Retina 5K 4GHz | 16GB R...",IMac desktop computer 27 inch Retina 5K 4GHz C...,4909.00,0,"5,74E+15"
2674,PAC1066,"Apple iMac 27 ""Core i5 3.3GHz Retina 5K | 32GB...",IMac desktop computer 27 inch 5K Retina i5 3.3...,3889.00,0,"5,74E+15"
7253,PAC2092,"Apple iMac 27 ""Core i5 3.5GHz Retina 5K | 64GB...",IMac desktop computer 27 inch Retina 5K RAM 64...,4339.00,0,"5,74E+15"
7239,PAC2137,"Apple iMac 27 ""Core i5 Retina 5K 35GHz | 16GB ...",IMac desktop computer 27 inch Retina 5K RAM 16...,2539.00,0,"5,74E+15"
7334,PAC2123,"Apple iMac 27 ""Core i7 Retina 5K 42GHz | 16GB ...",IMac desktop computer 27 inch Retina 5K RAM 16...,3799.00,0,"5,74E+15"
2631,APP1382,"Apple iMac 27 ""Core i7 Retina 5K 4GHz | 8GB | ...",IMac desktop computer 27 inch 5K Retina 8GB RA...,3649.00,0,"5,74E+15"
2834,PAC0970,"Apple iMac 27 ""Core i5 3.2GHz Retina 5K | 32GB...",IMac desktop computer 27 inch 5K Retina i5 3.2...,3409.00,0,"5,74E+15"
7324,PAC2134,"Apple iMac 27 ""Core i5 3.8GHz Retina 5K | 64GB...",IMac desktop computer 27 inch 5K Retina 64GB S...,5959.00,0,"5,74E+15"
2677,PAC1069,"Apple iMac 27 ""Core i7 Retina 5K 4Hz | 16GB | ...",IMac desktop computer 27 inch 5K Retina i5 3.3...,4189.00,0,"5,74E+15"
7284,PAC2107,"Apple iMac 27 ""Core i7 42GHz 5K Retina | 32GB ...",IMac desktop computer 27 inch Retina 5K RAM 32...,4165.59,0,"5,74E+15"
7305,APP2245,"Apple iMac 27 ""Core i7 Retina 5K 42Ghz | 8GB |...",IMac desktop computer 27 inch 5K Retina 8GB RA...,2839.00,0,"5,74E+15"
7259,PAC2100,"Apple iMac 27 ""Core i5 3.5GHz Retina 5K | 16GB...",IMac desktop computer 27 inch Retina 5K RAM 16...,2899.00,0,"5,74E+15"
2641,PAC1033,"Apple iMac 27 ""Core i7 Retina 5K 4GHz | 16GB |...",IMac desktop computer 27 inch 5K Retina 4GHz i...,3169.00,0,"5,74E+15"
2699,PAC1623,"Apple iMac 27 ""Core i5 3.3GHz Retina 5K | 16GB...",Desktop computer iMac 27-inch 3.3GHz Core i5 5...,4609.00,0,"5,74E+15"
7293,PAC2076,"Apple iMac 27 ""Core i5 3.4GHz Retina 5K | 16GB...",IMac desktop computer 27 inch Retina 5K RAM 16...,2459.00,0,"5,74E+15"
2683,PAC1607,"Apple iMac 27 ""Core i5 3.3GHz Retina 5K | 8GB ...",Desktop computer iMac 27-inch 3.3GHz Core i5 5...,3349.00,0,"5,74E+15"

In [ ]:
Looks like this category is full of desktop computers.

In [89]:
# product_category_df.loc[product_category_df["type"].str.contains("5,74E+15", case=False), "category"] = "desktop_computers" # this code was not working for the value in type
desktop_computers_mask = (
    product_category_df["type"]
    .astype(str)
    .str.contains("5,74E+15", case=False, na=False, regex=False)
)

product_category_df.loc[desktop_computers_mask, "category"] = "desktop_computers"
product_category_df["category"].value_counts()

category
                           4946
phone_cases                1057
servers                     939
it_hardware_accessories     783
storage                     562
smart_devices               454
laptops                     373
ipad_cases                  362
computer_cases              269
desktop_computers           247
Name: count, dtype: int64

In [90]:
category_type_df.loc[category_type_df["type"] == "1364"].sample(10)

,sku,name,desc,price,in_stock,type
708,CRU0023,Crucial Mac Memory 4GB DDR3 1333MHz SO-DIMM,4GB RAM Mac mini iMac (2010/11) and MacBook Pr...,53.99,1,1364
220,OWC0036-2,Mac memory OWC 8GB (2x4GB) SO-DIMM DDR3 1333MHZ,RAM 8GB (2x4GB) Mac mini (2011) iMac (2010-201...,93.98,1,1364
4961,CRU0048-4,Crucial memory Mac 64GB (4x16GB) DDR3 1867MHz ...,RAM 64GB (4x16GB) of 1867MHz for iMac 27 inch ...,939.96,0,1364
309,OWC0059,Mac OWC Memory 8GB (2x4GB) 800MHz DDR2 FB-DIMM,RAM 8GB (2x4GB) for Mac Pro 8-core.,169.99,0,1364
631,OWC0093,Mac OWC Memory 2GB 1333MHz DDR3 DIMM,2GB RAM Mac Pro (July / 2010).,20.99,1,1364
1907,FCM0005-2,Mac memory FCM 4GB (2x2GB) SO-DIMM DDR2 800 MHz,RAM 4GB (2x2gb) iMac with Intel Core 2 Duo (Pe...,60.00,0,1364
632,OWC0094,Mac OWC Memory 4GB DDR3 1333MHz DIMM,RAM 4GB Mac Pro 2009/2010.,34.99,1,1364
1901,FCM0009-2,FCM Mac Memory 8GB (2x4GB) 800MHz DDR2 FB-DIMM,RAM 8GB (2x4GB) for Mac Pro 8-core.,119.98,0,1364
2870,FCM0038-4,Mac memory FCM 32GB (4x8GB) SO-DIMM DDR3 1867MHz,Mac memory FCM 32GB (4x8GB) DDR3 1867MHz SO-DI...,607.92,0,1364
1502,CRU0037-4,Crucial Mac Memory 32GB (4x8GB) 1866MHz DDR3 DIMM,RAM 32GB (4x8GB) Mac Pro 2013.,463.96,0,1364

Looks like this category is full of RAM (memory).

In [91]:
product_category_df.loc[product_category_df["type"].str.contains("1364", case=False), "category"] = "ram_memories"
product_category_df["category"].value_counts()

category
                           4730
phone_cases                1057
servers                     939
it_hardware_accessories     783
storage                     562
smart_devices               454
laptops                     373
ipad_cases                  362
computer_cases              269
desktop_computers           247
ram_memories                216
Name: count, dtype: int64

In [92]:
category_type_df.loc[category_type_df["type"] == "12585395"].sample(10)

,sku,name,desc,price,in_stock,type
4991,GTE0073,G-Technology G-DRIVE ev FireWire Adapter Series,SATA adapter to FireWire 800 for ev Series wit...,51.01,0,12585395
6670,NDA0010,Nonda Mini USB-C to USB-A Space Gray,Mini USB-C USB adapter for MacBook,12.54,0,12585395
4084,BEL0229,Belkin Mini DisplayPort to DVI Adapter,Video Adapter Mini DisplayPort to DVI.,34.99,0,12585395
6169,SAT0023-A,Open - Satechi USB Hub-C to USB / Micro SD / S...,Reconditioned hub with two USB 3.0 SD Micro SD...,54.99,0,12585395
7216,AP20136,Second hand - Apple Travel Adapter Kit,Adapter kit with seven types of interchangeabl...,35.00,0,12585395
6102,STA0043,Startech charging cable Thunderbolt 3 05m Blac...,Cable length 05 m with connection Thunderbolt ...,33.99,1,12585395
9109,SAT0070,Satechi USB adapter to HDMI 4K-C 60Hz Plata,USB-C adapter with HDMI connection for Mac and PC,34.99,1,12585395
9924,STA0035-A,Open - Startech USB Hub-C or VGA to HDMI 4K US...,Hub with USB-C connection VGA port or HDMI 4K ...,123.99,0,12585395
6441,8MO0011,8Mobility iSlice Micro SD Adapter MacBook Pro ...,Micro SD card adapter for MacBook Pro Retina 1...,35.00,1,12585395
9829,HTE0013-A,Open - HyperJuice Battery 80Wh USB-C 4 x QC US...,Reconditioned Adapter 80W charging HyperJuice ...,79.95,0,12585395

Looks like this category is full of adapters.

In [93]:
product_category_df.loc[product_category_df["type"].str.contains("12585395", case=False), "category"] = "adapters"
product_category_df["category"].value_counts()

category
                           4540
phone_cases                1057
servers                     939
it_hardware_accessories     783
storage                     562
smart_devices               454
laptops                     373
ipad_cases                  362
computer_cases              269
desktop_computers           247
ram_memories                216
adapters                    190
Name: count, dtype: int64

In [94]:
category_type_df.loc[category_type_df["type"] == "1296"].sample(10)

,sku,name,desc,price,in_stock,type
7728,BNQ0055,"PD3200Q Monitor BenQ 32 ""LCD WQHD Professional...",Monitor 32 inch 100% sRGB height adjustable an...,466.00,1,1296
9864,LGE0062-A,Open - Lg-B 32UD59 MONITOR DCI-P3 95% 4K DP HDMI,Monitor Refurbished LG 32UD59-B 4K resolution ...,499.00,1,1296
3190,LGE0018,"LG 34UM67-P Monitor LCD 34 """,Monitor IPS ultrapanorámico 21: 9 34-inch.,599.00,0,1296
3571,BNQ0026,"GW2760HS Monitor BenQ Full HD 27 ""Black",Monitor HDMI FHD 27-inch LED VA and stylish fr...,199.00,0,1296
6937,SAM0091-A,"Open - Samsung S32D850T Monitor 32 ""WQHD DP VA",High resolution monitor screen division based ...,599.00,0,1296
610,BNQ0023,"Benq GL2460HM Monitor Full HD 24 ""Black",LCD Monitor 24-inch high-definition HDMI conne...,158.00,0,1296
8054,LGE0067,"43UD79-B LG Monitor 425 ""4K 72% NTSC USB-C Spe...",425 inch monitor 5ms response DisplayPort and ...,845.99,1,1296
2201,DLL0008,"Dell P2214H Monitor 215 ""IPS DP 1.2 pivotably",Monitor 215 adjustable inch high vision.,221.43,0,1296
3469,SAM0092,"Samsung S24E650 236 Monitor """,Monitor 236 inch FHD LED with wide viewing angle.,224.90,0,1296
3696,LGE0030,"LG 34UM88-P Monitor 34 ""IPS QHD Thunderbolt 2",Monitor 34 inches Thunderbolt 2 QHD adjustable...,699.00,1,1296

In [ ]:
Looks like this category is full of monitors

In [95]:
product_category_df.loc[product_category_df["type"].str.contains("1296", case=False), "category"] = "monitors"
product_category_df["category"].value_counts()

category
                           4353
phone_cases                1057
servers                     939
it_hardware_accessories     783
storage                     562
smart_devices               454
laptops                     373
ipad_cases                  362
computer_cases              269
desktop_computers           247
ram_memories                216
adapters                    190
monitors                    187
Name: count, dtype: int64

In [96]:
category_type_df.loc[category_type_df["type"] == "1325"].sample(10)

,sku,name,desc,price,in_stock,type
3200,KAN0051,USB-C Kanex Adapter USB-A female gray Space,USB-C-A USB cable Female for MacBook 12 inches...,24.99,0,1325
6690,SXA0011,SecurityXtra NoteSaver Security Cable 6mm Black,Security cable with two identical keys for Mac...,34.99,0,1325
150,NTE0012,NewerTech universal adapter IDE / SATA to USB 3.0,High speed universal adapter HDD / SSD to USB ...,54.99,1,1325
9977,AP20471,Apple Thunderbolt to FireWire 800 adapter,Reconditioned connection adapter Thunderbolt t...,35.00,0,1325
9078,BEL0343,Belkin Gigabit Ethernet Cable Cat. 6 2m,Ethernet Cable 2 meters Mac and PC Unit Class 6,9.99,1,1325
928,OTR0075,Startech Ethernet Cable Cat6 10m Black,Ethernet cable 10 meters Unit Class 6 Mac and PC.,11.99,1,1325
2408,MOS0154,Moshi Mini DisplayPort to HDMI Adapter compati...,Mini DisplayPort to HDMI adapter.,35.00,1,1325
3999,BEL0216,MIXIT Belkin Cable 3m Lightning to USB 2.4A White,Charging cable and synchronization Lightning t...,29.99,0,1325
152,NTE0014,NewerTech eSATA to USB 3.0 Adapter,High-speed eSATA adapter to USB 3.0.,36.99,0,1325
8284,AP20139,Like new - Apple Power Adapter Cable,Cable for MacBook long as new for current.,25.00,0,1325

Looks like this category is full of cables

In [97]:
product_category_df.loc[product_category_df["type"].str.contains("1325", case=False), "category"] = "cables"
product_category_df["category"].value_counts()

category
                           4170
phone_cases                1057
servers                     939
it_hardware_accessories     783
storage                     562
smart_devices               454
laptops                     373
ipad_cases                  362
computer_cases              269
desktop_computers           247
ram_memories                216
adapters                    190
monitors                    187
cables                      183
Name: count, dtype: int64


I wonder how many `type`s account for most of our products?

In [37]:
n = 30
print(f"With the {n} largest types, we account for {((category_type_df.groupby('type').count().nlargest(n, 'sku')['sku'].sum()) / (category_type_df.shape[0]) * 100).round(2)}% of all products.")

With the 30 largest types, we account for 78.4% of all products.

Looks like we can simply investigate 30 types and set the categories, then the remaining 20% of products can have the category `other`.

Use the skills you learnt above to change the category for each type.